# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Proekt.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from DopProekt import Ui_InstructionForm
from functools import partial
from math import factorial


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(440, 408)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.table = QtWidgets.QLCDNumber(self.centralwidget)
        self.table.setGeometry(QtCore.QRect(10, 40, 431, 71))
        self.table.setObjectName("table")
        self.btn1 = QtWidgets.QPushButton(self.centralwidget)
        self.btn1.setGeometry(QtCore.QRect(10, 110, 61, 51))
        self.btn1.setObjectName("btn1")
        self.btn2 = QtWidgets.QPushButton(self.centralwidget)
        self.btn2.setGeometry(QtCore.QRect(70, 110, 61, 51))
        self.btn2.setObjectName("btn2")
        self.btn3 = QtWidgets.QPushButton(self.centralwidget)
        self.btn3.setGeometry(QtCore.QRect(130, 110, 61, 51))
        self.btn3.setObjectName("btn3")
        self.btn6 = QtWidgets.QPushButton(self.centralwidget)
        self.btn6.setGeometry(QtCore.QRect(130, 160, 61, 51))
        self.btn6.setObjectName("btn6")
        self.btn5 = QtWidgets.QPushButton(self.centralwidget)
        self.btn5.setGeometry(QtCore.QRect(70, 160, 61, 51))
        self.btn5.setObjectName("btn5")
        self.btn4 = QtWidgets.QPushButton(self.centralwidget)
        self.btn4.setGeometry(QtCore.QRect(10, 160, 61, 51))
        self.btn4.setObjectName("btn4")
        self.btn9 = QtWidgets.QPushButton(self.centralwidget)
        self.btn9.setGeometry(QtCore.QRect(130, 210, 61, 51))
        self.btn9.setObjectName("btn9")
        self.btn8 = QtWidgets.QPushButton(self.centralwidget)
        self.btn8.setGeometry(QtCore.QRect(70, 210, 61, 51))
        self.btn8.setObjectName("btn8")
        self.btn7 = QtWidgets.QPushButton(self.centralwidget)
        self.btn7.setGeometry(QtCore.QRect(10, 210, 61, 51))
        self.btn7.setObjectName("btn7")
        self.btn0 = QtWidgets.QPushButton(self.centralwidget)
        self.btn0.setGeometry(QtCore.QRect(10, 260, 61, 51))
        self.btn0.setObjectName("btn0")
        self.btntochka = QtWidgets.QPushButton(self.centralwidget)
        self.btntochka.setGeometry(QtCore.QRect(70, 260, 61, 51))
        self.btntochka.setObjectName("btntochka")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(190, 110, 123, 231))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btnplus = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btnplus.setObjectName("btnplus")
        self.verticalLayout.addWidget(self.btnplus)
        self.btnminus = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btnminus.setObjectName("btnminus")
        self.verticalLayout.addWidget(self.btnminus)
        self.btnymno = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btnymno.setObjectName("btnymno")
        self.verticalLayout.addWidget(self.btnymno)
        self.btndelen = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btndelen.setObjectName("btndelen")
        self.verticalLayout.addWidget(self.btndelen)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(310, 109, 131, 231))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.btnfact = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.btnfact.setObjectName("btnfact")
        self.verticalLayout_2.addWidget(self.btnfact)
        self.btnabc = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.btnabc.setObjectName("btnabc")
        self.verticalLayout_2.addWidget(self.btnabc)
        self.btnsqrt = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.btnsqrt.setObjectName("btnsqrt")
        self.verticalLayout_2.addWidget(self.btnsqrt)
        self.btndiv = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.btndiv.setObjectName("btndiv")
        self.verticalLayout_2.addWidget(self.btndiv)
        self.btnmod = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.btnmod.setObjectName("btnmod")
        self.verticalLayout_2.addWidget(self.btnmod)
        self.btnplusminus = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.btnplusminus.setObjectName("btnplusminus")
        self.verticalLayout_2.addWidget(self.btnplusminus)
        self.btnkvadrat = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.btnkvadrat.setObjectName("btnkvadrat")
        self.verticalLayout_2.addWidget(self.btnkvadrat)
        self.btnС = QtWidgets.QPushButton(self.centralwidget)
        self.btnС.setGeometry(QtCore.QRect(190, 340, 121, 31))
        self.btnС.setObjectName("btnС")
        self.btnravno = QtWidgets.QPushButton(self.centralwidget)
        self.btnravno.setGeometry(QtCore.QRect(310, 340, 121, 31))
        self.btnravno.setObjectName("btnravno")
        self.graphcalc = QtWidgets.QPushButton(self.centralwidget)
        self.graphcalc.setGeometry(QtCore.QRect(100, 0, 111, 41))
        self.graphcalc.setObjectName("graphcalc")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 440, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action = QtWidgets.QAction(MainWindow)
        self.action.setObjectName("action")
        self.action_2 = QtWidgets.QAction(MainWindow)
        self.action_2.setObjectName("action_2")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.btnС.setStyleSheet("background-color: rgb(252, 156, 0);")
        self.current_od = [[], "", []]
        self.one = True
        self.graphcalc.clicked.connect(self.get_instruction)
        self.btn0.clicked.connect(partial(self.add_to_table, self.btn0.text()))
        self.btn1.clicked.connect(partial(self.add_to_table, self.btn1.text()))
        self.btn2.clicked.connect(partial(self.add_to_table, self.btn2.text()))
        self.btn3.clicked.connect(partial(self.add_to_table, self.btn3.text()))
        self.btn4.clicked.connect(partial(self.add_to_table, self.btn4.text()))
        self.btn5.clicked.connect(partial(self.add_to_table, self.btn5.text()))
        self.btn6.clicked.connect(partial(self.add_to_table, self.btn6.text()))
        self.btn7.clicked.connect(partial(self.add_to_table, self.btn7.text()))
        self.btn8.clicked.connect(partial(self.add_to_table, self.btn8.text()))
        self.btn9.clicked.connect(partial(self.add_to_table, self.btn9.text()))
        self.btntochka.clicked.connect(partial(self.add_to_table, self.btntochka.text()))
        self.btnravno.clicked.connect(self.equals)
        self.btndelen.clicked.connect(partial(self.prod, self.btndelen.text()))
        self.btnplus.clicked.connect(partial(self.prod, self.btnplus.text()))
        self.btnminus.clicked.connect(partial(self.prod, self.btnminus.text()))
        self.btnymno.clicked.connect(partial(self.prod, self.btnymno.text()))
        self.btnkvadrat.clicked.connect(partial(self.prod, self.btnkvadrat.text()))
        self.btnfact.clicked.connect(self.fact_prod)
        self.btnС.clicked.connect(self.clear)
        self.btnabc.clicked.connect(self.abs_prod)
        self.btnplusminus.clicked.connect(self.plus_minus)
        self.btnsqrt.clicked.connect(self.sqrt_prod)
        self.btndiv.clicked.connect(partial(self.prod, self.btndiv.text()))
        self.btnmod.clicked.connect(partial(self.prod, self.btnmod.text()))
#Начало

    def add_to_table(self, od):
        self.x = len(self.current_od)
        if od == "." and self.x != 0:
            if self.current_od[0].count(".") >= 1 and self.one:
                pass
            elif self.current_od[2].count(".") >= 1:
                pass
            else:
                if self.one:
                    self.current_od[0].append(".")
                    self.table.display("".join(self.current_od[0]))
                else:
                    self.current_od[2].append(".")
                    self.table.display("".join(self.current_od[2]))
        elif od in ['1', '2', '3', '4', '5', '6', '7', '8', '9', '0']:
            if self.one:
                self.current_od[0].append(od)
                self.table.display("".join(self.current_od[0]))
            else:
                self.current_od[2].append(od)
                self.table.display("".join(self.current_od[2]))

    def prod(self, od):
        if self.current_od[0] != []:
            if od == "x^n":
                od = "**"
            self.one = False
            self.current_od[0] = "".join(self.current_od[0])
            self.current_od[1] = od

    def plus_minus(self):
        if self.one and self.current_od[0] != []:
            if self.current_od[0][0] == "-":
                del self.current_od[0][0]
                self.table.display("".join(self.current_od[0]))
            else:
                self.current_od[0].insert(0, "-")
                self.table.display("".join(self.current_od[0]))
        elif self.current_od[2] != []:
            if self.current_od[2][0] == "-":
                del self.current_od[2][0]
                self.table.display("".join(self.current_od[2]))
            else:
                self.current_od[2].insert(0, "-")
                self.table.display("".join(self.current_od[2]))


    def fact_prod(self):
        try:
            x = int("".join(self.current_od[0]))
            self.current_od = str(factorial(int("".join(self.current_od[0]))))
        except BaseException:
            self.current_od = "Error"

        self.table.display(self.current_od)

    def equals(self):
        self.current_od[2] = "".join(self.current_od[2])
        if (self.current_od[1] == "/" or self.current_od[1] == "//" or self.current_od[1] == "%") and \
                self.current_od[2] == "0":
            self.table.display("Error")
        else:
            self.table.display(eval("".join(self.current_od)))

    def sqrt_prod(self):
        if int("".join(self.current_od[0])) < 0:
            self.table.display("Error")
        else:
            self.current_od[0] = str(int("".join(self.current_od[0])) ** 0.5)
            self.table.display(self.current_od[0])

    def abs_prod(self):
        if self.current_od[0] != []:
            self.table.display(abs(float("".join(self.current_od[0]))))

    def clear(self):
        self.current_od = [[], "", []]
        self.one = True
        self.table.display("")

    def get_instruction(self):
        self.instruction = Ui_InstructionForm(self)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn1.setText(_translate("MainWindow", "1"))
        self.btn2.setText(_translate("MainWindow", "2"))
        self.btn3.setText(_translate("MainWindow", "3"))
        self.btn6.setText(_translate("MainWindow", "6"))
        self.btn5.setText(_translate("MainWindow", "5"))
        self.btn4.setText(_translate("MainWindow", "4"))
        self.btn9.setText(_translate("MainWindow", "9"))
        self.btn8.setText(_translate("MainWindow", "8"))
        self.btn7.setText(_translate("MainWindow", "7"))
        self.btn0.setText(_translate("MainWindow", "0"))
        self.btntochka.setText(_translate("MainWindow", "."))
        self.btnplus.setText(_translate("MainWindow", "+"))
        self.btnminus.setText(_translate("MainWindow", "-"))
        self.btnymno.setText(_translate("MainWindow", "*"))
        self.btndelen.setText(_translate("MainWindow", "/"))
        self.btnfact.setText(_translate("MainWindow", "!x"))
        self.btnabc.setText(_translate("MainWindow", "|x|"))
        self.btnsqrt.setText(_translate("MainWindow", "√x"))
        self.btndiv.setText(_translate("MainWindow", "//"))
        self.btnmod.setText(_translate("MainWindow", "%"))
        self.btnkvadrat.setText(_translate("MainWindow", "x^n"))
        self.btnС.setText(_translate("MainWindow", "С"))
        self.btnravno.setText(_translate("MainWindow", "="))
        self.graphcalc.setText(_translate("MainWindow", "Граф. калькулятор"))
        self.action.setText(_translate("MainWindow", "Правила ввода мат. формул"))
        self.action_2.setText(_translate("MainWindow", "Графический калькулятор"))
        self.btnplusminus.setText(_translate("MainWindow", "+/-"))
